### Numpy

In [1]:
import numpy as np

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [6]:
x = np.full((5,5), 4)

In [8]:
x.shape

(5, 5)

In [9]:
x

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [10]:
y = np.eye(5)

In [11]:
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
y.shape

(5, 5)

In [16]:
### creating a matrix with diagonal elements 1, 2, 3, 4 ,5
z = np.diag([1, 2, 3, 4, 5])

In [17]:
z

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [18]:
z.shape

(5, 5)

Creating a rank 1 ndarray that has sequential integers

In [19]:
m = np.arange(10)

In [20]:
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
m.shape

(10,)

In [23]:
### defining the range of elements
arr = np.arange(4, 10)
arr

array([4, 5, 6, 7, 8, 9])

Creating a rank 1 ndarray containing evenly spaced integers within a certain range

In [24]:
x = np.arange(23, 50, 7)
x

array([23, 30, 37, 44])

To exclude the endpoints we pass <b>endpoint=False</b> to the method <b>linspace()</b>

In [26]:
arr = np.linspace(55, 100, 5, endpoint=False)
arr

array([55., 64., 73., 82., 91.])

In [28]:
np.reshape(x,(2,2))

array([[23, 30],
       [37, 44]])

In [30]:
X = np.arange(20)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.reshape(X,(4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
np.reshape(X,(2,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [39]:
val = np.random.random((3,3))
val

array([[0.71291972, 0.14539446, 0.65690381],
       [0.17799002, 0.43354678, 0.82258522],
       [0.69500069, 0.69557704, 0.71361895]])

In [50]:
mat = np.random.randint(4,10, size=(3,3))
mat

array([[8, 5, 9],
       [6, 5, 9],
       [7, 5, 7]])

Creating a 20 x 20 ndarray of random floating point numbers drawn from a normal distribution with a mean (average) of zero and a standard deviation of 0.1.

In [55]:
arr1 = np.random.normal(0, 0.1, size=(10, 10))
arr1

array([[ 0.01636265, -0.04014637, -0.0772138 ,  0.03387651,  0.05506356,
         0.01028101, -0.06667078, -0.18795761,  0.09803371, -0.08909931],
       [ 0.10988515, -0.07551296,  0.06525029, -0.03906363,  0.07973204,
        -0.04688774, -0.10969966, -0.03569025, -0.00797287, -0.07271621],
       [ 0.08767597, -0.11196326,  0.02549369, -0.16472042, -0.04747099,
         0.11821078, -0.01898791,  0.01839965, -0.03207166,  0.08774868],
       [ 0.13700193,  0.01984727, -0.23596446,  0.01853114, -0.03457862,
        -0.03397023, -0.05135538,  0.10715655,  0.0276395 , -0.11560214],
       [ 0.16961584,  0.00904633,  0.05977592,  0.07687208,  0.19274042,
         0.05344379, -0.25568237,  0.12953459, -0.05845986,  0.04184263],
       [ 0.0393984 ,  0.01703815,  0.10598267, -0.09698046,  0.09456034,
         0.00413135,  0.11414991,  0.00550188, -0.02384901, -0.00671316],
       [-0.11601607, -0.04600571,  0.01715932,  0.00833671,  0.0512428 ,
         0.05757135, -0.03250577, -0.0219792 

In [59]:
# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2, 34, 2).reshape(4, 4)
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [70]:
Y = np.linspace(2, 32, 16).reshape(4,4)
Y

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [71]:
Z  = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
m = np.delete(Z, [0, 4])
m

array([2, 3, 4, 6, 7, 8, 9])

In [73]:
m = np.delete(m, [0])
m

array([3, 4, 6, 7, 8, 9])

In [79]:
n = m.reshape(1, 6)
n

array([[3, 4, 6, 7, 8, 9]])

In [80]:
np.append(n, 12)

array([ 3,  4,  6,  7,  8,  9, 12])

In [81]:
Y

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [82]:
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [83]:
w = np.insert(X, 1, 5, axis=1)

In [84]:
w

array([[ 2,  5,  4,  6,  8],
       [10,  5, 12, 14, 16],
       [18,  5, 20, 22, 24],
       [26,  5, 28, 30, 32]])

In [85]:
np.insert(X, 2, 5, axis=0)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 5,  5,  5,  5],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [86]:
np.insert(X, 2, [3,4])

array([ 2,  4,  3,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
       32])

In [127]:
ar = np.arange(2, 41, 2)
ar.reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [116]:
# We insert a row between the first and last row of y
w = np.insert(ar, 1, [4,5,6],axis=0)
print(w)
print(w.shape)

[ 2  4  5  6  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
(23,)


In [129]:
ar.reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [134]:
# We insert a column full of 5s between the first and second column of y
np.insert(ar, 2, 9, axis=0)

array([ 2,  4,  9,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [135]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [138]:
ar1 = np.arange(20).reshape(4,5)
ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [139]:
np.diag(ar1)

array([ 0,  6, 12, 18])

In [152]:
arx = np.random.randint(1,12, size=(3,4))
arx

array([[ 9,  3, 10,  7],
       [ 9,  2,  6, 10],
       [ 4,  9,  1,  4]])

In [153]:
np.sort(arx)

array([[ 3,  7,  9, 10],
       [ 2,  6,  9, 10],
       [ 1,  4,  4,  9]])

In [154]:
arx

array([[ 9,  3, 10,  7],
       [ 9,  2,  6, 10],
       [ 4,  9,  1,  4]])

In [155]:
arx.sort()

In [156]:
arx

array([[ 3,  7,  9, 10],
       [ 2,  6,  9, 10],
       [ 1,  4,  4,  9]])

In [161]:
num = np.arange(1,26).reshape(5,5)
num

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [162]:
odd = num[(num % 2) != 0]
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [163]:
odd.mean()

13.0

In [164]:
num.mean(axis=0)

array([11., 12., 13., 14., 15.])

In [165]:
num.mean(axis=1)

array([ 3.,  8., 13., 18., 23.])

In [166]:
num.sum(axis=0)

array([55, 60, 65, 70, 75])

In [167]:
num.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [168]:
num

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [169]:
print('Standard Deviation of all elements in the columns of X:', num.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', num.std(axis=1))

Standard Deviation of all elements in the columns of X: [7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]
Standard Deviation of all elements in the rows of X: [1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]


In [170]:
num.max()

25

In [171]:
num.max(axis=1)

array([ 5, 10, 15, 20, 25])

In [172]:
num.min(axis=0)

array([1, 2, 3, 4, 5])

In [173]:
numbers = np.random.randint(10,50, size=(7,7))
numbers

array([[35, 27, 37, 49, 12, 26, 42],
       [11, 34, 28, 48, 19, 33, 24],
       [25, 41, 13, 15, 32, 19, 32],
       [46, 27, 20, 10, 46, 29, 44],
       [11, 22, 24, 42, 44, 18, 40],
       [25, 23, 40, 36, 17, 26, 29],
       [42, 15, 13, 19, 15, 34, 28]])

In [174]:
numbers.min()

10

In [175]:
numbers.max()

49

In [176]:
numbers.max(axis=1)

array([49, 48, 41, 46, 44, 40, 42])

In [177]:
numbers.max(axis=0)

array([46, 41, 40, 49, 46, 34, 44])

In [178]:
np.arange(1,5)

array([1, 2, 3, 4])

In [180]:
np.ones((4,4))*np.arange(1,5)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [181]:
np.arange(1,5)

array([1, 2, 3, 4])

In [182]:
np.dot(np.arange(1,5), np.ones((4,4)))

array([10., 10., 10., 10.])

### Pandas

In [183]:
import pandas as pd

In [184]:
groceries = pd.Series(data=[30, 6, 'Yes', 'No'], index=['eggs', 'apples', 'milk', 'bread'])
groceries

eggs       30
apples      6
milk      Yes
bread      No
dtype: object

In [185]:
groceries.shape

(4,)

In [186]:
'apple' in groceries

False

In [187]:
groceries[['milk', 'eggs']]

milk    Yes
eggs     30
dtype: object

In [188]:
groceries.loc[['eggs', 'apples']]

eggs      30
apples     6
dtype: object

In [189]:
groceries[[-1]]

bread    No
dtype: object

In [190]:
groceries['eggs'] = 10

In [191]:
groceries.drop('apples')

eggs      10
milk     Yes
bread     No
dtype: object

In [192]:
groceries

eggs       10
apples      6
milk      Yes
bread      No
dtype: object

In [193]:
groceries.drop('apples', inplace=True)

In [194]:
groceries

eggs      10
milk     Yes
bread     No
dtype: object

In [ ]:
groceries