# Numpy

In [1]:
import numpy as np

In [3]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.full((2,3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

In [6]:
x = np.full((5,5), 4)

In [8]:
x.shape

(5, 5)

In [9]:
x

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [10]:
y = np.eye(5)

In [11]:
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
y.shape

(5, 5)

In [16]:
### creating a matrix with diagonal elements 1, 2, 3, 4 ,5
z = np.diag([1, 2, 3, 4, 5])

In [17]:
z

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [18]:
z.shape

(5, 5)

Creating a rank 1 ndarray that has sequential integers

In [19]:
m = np.arange(10)

In [20]:
m

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
m.shape

(10,)

In [23]:
### defining the range of elements
arr = np.arange(4, 10)
arr

array([4, 5, 6, 7, 8, 9])

Creating a rank 1 ndarray containing evenly spaced integers within a certain range

In [24]:
x = np.arange(23, 50, 7)
x

array([23, 30, 37, 44])

To exclude the endpoints we pass <b>endpoint=False</b> to the method <b>linspace()</b>

In [26]:
arr = np.linspace(55, 100, 5, endpoint=False)
arr

array([55., 64., 73., 82., 91.])

In [28]:
np.reshape(x,(2,2))

array([[23, 30],
       [37, 44]])

In [30]:
X = np.arange(20)
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [31]:
np.reshape(X,(4,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [33]:
np.reshape(X,(2,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [39]:
val = np.random.random((3,3))
val

array([[0.71291972, 0.14539446, 0.65690381],
       [0.17799002, 0.43354678, 0.82258522],
       [0.69500069, 0.69557704, 0.71361895]])

In [50]:
mat = np.random.randint(4,10, size=(3,3))
mat

array([[8, 5, 9],
       [6, 5, 9],
       [7, 5, 7]])

Creating a 20 x 20 ndarray of random floating point numbers drawn from a normal distribution with a mean (average) of zero and a standard deviation of 0.1.

In [55]:
arr1 = np.random.normal(0, 0.1, size=(10, 10))
arr1

array([[ 0.01636265, -0.04014637, -0.0772138 ,  0.03387651,  0.05506356,
         0.01028101, -0.06667078, -0.18795761,  0.09803371, -0.08909931],
       [ 0.10988515, -0.07551296,  0.06525029, -0.03906363,  0.07973204,
        -0.04688774, -0.10969966, -0.03569025, -0.00797287, -0.07271621],
       [ 0.08767597, -0.11196326,  0.02549369, -0.16472042, -0.04747099,
         0.11821078, -0.01898791,  0.01839965, -0.03207166,  0.08774868],
       [ 0.13700193,  0.01984727, -0.23596446,  0.01853114, -0.03457862,
        -0.03397023, -0.05135538,  0.10715655,  0.0276395 , -0.11560214],
       [ 0.16961584,  0.00904633,  0.05977592,  0.07687208,  0.19274042,
         0.05344379, -0.25568237,  0.12953459, -0.05845986,  0.04184263],
       [ 0.0393984 ,  0.01703815,  0.10598267, -0.09698046,  0.09456034,
         0.00413135,  0.11414991,  0.00550188, -0.02384901, -0.00671316],
       [-0.11601607, -0.04600571,  0.01715932,  0.00833671,  0.0512428 ,
         0.05757135, -0.03250577, -0.0219792 

In [59]:
# Using the Built-in functions you learned about in the
# previous lesson, create a 4 x 4 ndarray that only
# contains consecutive even numbers from 2 to 32 (inclusive)

X = np.arange(2, 34, 2).reshape(4, 4)
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [70]:
Y = np.linspace(2, 32, 16).reshape(4,4)
Y

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [71]:
Z  = np.array([[1,2,3],[4,5,6],[7,8,9]])
Z

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [72]:
m = np.delete(Z, [0, 4])
m

array([2, 3, 4, 6, 7, 8, 9])

In [73]:
m = np.delete(m, [0])
m

array([3, 4, 6, 7, 8, 9])

In [79]:
n = m.reshape(1, 6)
n

array([[3, 4, 6, 7, 8, 9]])

In [80]:
np.append(n, 12)

array([ 3,  4,  6,  7,  8,  9, 12])

In [81]:
Y

array([[ 2.,  4.,  6.,  8.],
       [10., 12., 14., 16.],
       [18., 20., 22., 24.],
       [26., 28., 30., 32.]])

In [82]:
X

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [83]:
w = np.insert(X, 1, 5, axis=1)

In [84]:
w

array([[ 2,  5,  4,  6,  8],
       [10,  5, 12, 14, 16],
       [18,  5, 20, 22, 24],
       [26,  5, 28, 30, 32]])

In [85]:
np.insert(X, 2, 5, axis=0)

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [ 5,  5,  5,  5],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [86]:
np.insert(X, 2, [3,4])

array([ 2,  4,  3,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30,
       32])

In [127]:
ar = np.arange(2, 41, 2)
ar.reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [116]:
# We insert a row between the first and last row of y
w = np.insert(ar, 1, [4,5,6],axis=0)
print(w)
print(w.shape)

[ 2  4  5  6  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40]
(23,)


In [129]:
ar.reshape(4,5)

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [134]:
# We insert a column full of 5s between the first and second column of y
np.insert(ar, 2, 9, axis=0)

array([ 2,  4,  9,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40])

In [135]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [138]:
ar1 = np.arange(20).reshape(4,5)
ar1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [139]:
np.diag(ar1)

array([ 0,  6, 12, 18])

In [152]:
arx = np.random.randint(1,12, size=(3,4))
arx

array([[ 9,  3, 10,  7],
       [ 9,  2,  6, 10],
       [ 4,  9,  1,  4]])

In [153]:
np.sort(arx)

array([[ 3,  7,  9, 10],
       [ 2,  6,  9, 10],
       [ 1,  4,  4,  9]])

In [154]:
arx

array([[ 9,  3, 10,  7],
       [ 9,  2,  6, 10],
       [ 4,  9,  1,  4]])

In [155]:
arx.sort()

In [156]:
arx

array([[ 3,  7,  9, 10],
       [ 2,  6,  9, 10],
       [ 1,  4,  4,  9]])

In [161]:
num = np.arange(1,26).reshape(5,5)
num

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [162]:
odd = num[(num % 2) != 0]
odd

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

In [163]:
odd.mean()

13.0

In [164]:
num.mean(axis=0)

array([11., 12., 13., 14., 15.])

In [165]:
num.mean(axis=1)

array([ 3.,  8., 13., 18., 23.])

In [166]:
num.sum(axis=0)

array([55, 60, 65, 70, 75])

In [167]:
num.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [168]:
num

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [169]:
print('Standard Deviation of all elements in the columns of X:', num.std(axis=0))
print('Standard Deviation of all elements in the rows of X:', num.std(axis=1))

Standard Deviation of all elements in the columns of X: [7.07106781 7.07106781 7.07106781 7.07106781 7.07106781]
Standard Deviation of all elements in the rows of X: [1.41421356 1.41421356 1.41421356 1.41421356 1.41421356]


In [170]:
num.max()

25

In [171]:
num.max(axis=1)

array([ 5, 10, 15, 20, 25])

In [172]:
num.min(axis=0)

array([1, 2, 3, 4, 5])

In [173]:
numbers = np.random.randint(10,50, size=(7,7))
numbers

array([[35, 27, 37, 49, 12, 26, 42],
       [11, 34, 28, 48, 19, 33, 24],
       [25, 41, 13, 15, 32, 19, 32],
       [46, 27, 20, 10, 46, 29, 44],
       [11, 22, 24, 42, 44, 18, 40],
       [25, 23, 40, 36, 17, 26, 29],
       [42, 15, 13, 19, 15, 34, 28]])

In [174]:
numbers.min()

10

In [175]:
numbers.max()

49

In [176]:
numbers.max(axis=1)

array([49, 48, 41, 46, 44, 40, 42])

In [177]:
numbers.max(axis=0)

array([46, 41, 40, 49, 46, 34, 44])

In [178]:
np.arange(1,5)

array([1, 2, 3, 4])

In [180]:
np.ones((4,4))*np.arange(1,5)

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [181]:
np.arange(1,5)

array([1, 2, 3, 4])

In [182]:
np.dot(np.arange(1,5), np.ones((4,4)))

array([10., 10., 10., 10.])

# Pandas

In [13]:
import pandas as pd
import numpy as np

In [184]:
groceries = pd.Series(data=[30, 6, 'Yes', 'No'], index=['eggs', 'apples', 'milk', 'bread'])
groceries

eggs       30
apples      6
milk      Yes
bread      No
dtype: object

In [185]:
groceries.shape

(4,)

In [186]:
'apple' in groceries

False

In [187]:
groceries[['milk', 'eggs']]

milk    Yes
eggs     30
dtype: object

In [188]:
groceries.loc[['eggs', 'apples']]

eggs      30
apples     6
dtype: object

In [189]:
groceries[[-1]]

bread    No
dtype: object

In [190]:
groceries['eggs'] = 10

In [191]:
groceries.drop('apples')

eggs      10
milk     Yes
bread     No
dtype: object

In [192]:
groceries

eggs       10
apples      6
milk      Yes
bread      No
dtype: object

In [193]:
groceries.drop('apples', inplace=True)

In [194]:
groceries

eggs      10
milk     Yes
bread     No
dtype: object

<b>Create a Pandas Series that contains the distance of some planets from the Sun.  Use the name of the planets as the index to your Pandas Series, and the distance from the Sun as your data. The distance from the Sun is in units of 10^6 km

distance_from_sun = [149.6, 1433.5, 227.9, 108.2, 778.6]

planets = ['Earth','Saturn', 'Mars','Venus', 'Jupiter']

Create a Pandas Series using the above data, with the name of the planets as the index and the distance from the Sun as your data.  </b> <br>
dist_planets = 

In [4]:
distance_from_sun = [149.6, 1433.5, 227.9, 108.2, 778.6]
planets = ['Earth','Saturn', 'Mars','Venus', 'Jupiter']
dist_planets = pd.Series(data=distance_from_sun, index=planets)
dist_planets

Earth       149.6
Saturn     1433.5
Mars        227.9
Venus       108.2
Jupiter     778.6
dtype: float64

<b> Calculate the number of minutes it takes sunlight to reach each planet. You can do this by dividing the distance from the Sun for each planet by the speed of light. Since in the data above the distance from the Sun is in units of 10^6 km, you can use a value for the speed of light of c = 18, since light travels 18 x 10^6 km/minute. </b> <br>
time_light = 

In [17]:
time_light = dist_planets[0:4] / 18

In [18]:
time_light

Earth      8.311111
Saturn    79.638889
Mars      12.661111
Venus      6.011111
dtype: float64

<b>Use Boolean indexing to select only those planets for which sunlight takes less than 40 minutes to reach them. </b> <br>
close_planets = 

In [19]:
close_planets = time_light[(time_light) < 40 ]
close_planets

Earth     8.311111
Mars     12.661111
Venus     6.011111
dtype: float64

## Panda's DataFrame

In [21]:
items = {'Bob' : pd.Series(data = [245, 25, 55], index = ['bike', 'pants', 'watch']),
         'Alice' : pd.Series(data = [40, 110, 500, 45], index = ['book', 'glasses', 'bike', 'pants'])}

In [23]:
type(items)

dict

In [25]:
shopping_carts = pd.DataFrame(items)
shopping_carts

Bob  Alice
bike     245.0  500.0
book       NaN   40.0
glasses    NaN  110.0
pants     25.0   45.0
watch     55.0    NaN

In [26]:
pd.DataFrame(shopping_carts, columns=['Bob'])

Bob
bike     245.0
book       NaN
glasses    NaN
pants     25.0
watch     55.0

In [45]:
similar_items = pd.DataFrame(items, index=['pants', 'book'])
similar_items

Bob  Alice
pants  25.0     45
book    NaN     40

In [46]:
shopping_carts.index

Index(['bike', 'book', 'glasses', 'pants', 'watch'], dtype='object')

In [47]:
data = {'Integers' : [1,2,3],
        'Floats' : [4.5, 8.2, 9.6]}
df = pd.DataFrame(data)
df

Integers  Floats
0         1     4.5
1         2     8.2
2         3     9.6

In [48]:
df = pd.DataFrame(data, index=['label 1', 'label 2', 'label 3'])
df

Integers  Floats
label 1         1     4.5
label 2         2     8.2
label 3         3     9.6

In [49]:
items2 = [{'bikes': 20, 'pants': 30, 'watches': 35}, 
          {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5}]
store_items = pd.DataFrame(items2)
store_items

bikes  pants  watches  glasses
0     20     30       35      NaN
1     15      5       10     50.0

In [50]:
store_items = pd.DataFrame(items2, index=['Store 1', 'Store 2'])
store_items

bikes  pants  watches  glasses
Store 1     20     30       35      NaN
Store 2     15      5       10     50.0

In [51]:
# creating a new columns 'Shirts' and adding 15 and 2 shirts
# for each stores respectively
store_items['shirts'] = [15, 2]
store_items.drop('Shirts', inplace=True, axis=1)

KeyError: "['Shirts'] not found in axis"

In [42]:
store_items

bikes  pants  watches  glasses  shirts
Store 1     20     30       35      NaN      15
Store 2     15      5       10     50.0       2

In [52]:
store_items['suits'] = store_items['shirts'] + store_items['pants'] 
store_items

bikes  pants  watches  glasses  shirts  suits
Store 1     20     30       35      NaN      15     45
Store 2     15      5       10     50.0       2      7

In [53]:
new_items = [{'bikes': 20, 'pants': 30, 'watches': 35, 'glasses': 4}]
new_items = pd.DataFrame(new_items, index=['Store 3'])
new_items

bikes  pants  watches  glasses
Store 3     20     30       35        4

In [54]:
store_items = store_items.append(new_items)
store_items

bikes  pants  watches  glasses  shirts  suits
Store 1     20     30       35      NaN    15.0   45.0
Store 2     15      5       10     50.0     2.0    7.0
Store 3     20     30       35      4.0     NaN    NaN

#### Adding new watches columns for store 2 and 3

In [55]:
store_items['new watches'] = store_items['watches'][1:]
store_items

bikes  pants  watches  glasses  shirts  suits  new watches
Store 1     20     30       35      NaN    15.0   45.0          NaN
Store 2     15      5       10     50.0     2.0    7.0         10.0
Store 3     20     30       35      4.0     NaN    NaN         35.0

In [56]:
store_items.insert(4, 'shoes', [8, 5, 0])
store_items

bikes  pants  watches  glasses  shoes  shirts  suits  new watches
Store 1     20     30       35      NaN      8    15.0   45.0          NaN
Store 2     15      5       10     50.0      5     2.0    7.0         10.0
Store 3     20     30       35      4.0      0     NaN    NaN         35.0

#### Deleting columns using 'pop' and 'drop' method

In [57]:
store_items.pop('new watches')
store_items

bikes  pants  watches  glasses  shoes  shirts  suits
Store 1     20     30       35      NaN      8    15.0   45.0
Store 2     15      5       10     50.0      5     2.0    7.0
Store 3     20     30       35      4.0      0     NaN    NaN

In [58]:
store_items.drop(['watches', 'shoes'], axis=1)
store_items

bikes  pants  watches  glasses  shoes  shirts  suits
Store 1     20     30       35      NaN      8    15.0   45.0
Store 2     15      5       10     50.0      5     2.0    7.0
Store 3     20     30       35      4.0      0     NaN    NaN

In [59]:
store_items = store_items.rename(columns={'bikes': 'hats'})
store_items

hats  pants  watches  glasses  shoes  shirts  suits
Store 1    20     30       35      NaN      8    15.0   45.0
Store 2    15      5       10     50.0      5     2.0    7.0
Store 3    20     30       35      4.0      0     NaN    NaN

In [60]:
store_items = store_items.rename(index={'Store 3':'last store'})
store_items

hats  pants  watches  glasses  shoes  shirts  suits
Store 1       20     30       35      NaN      8    15.0   45.0
Store 2       15      5       10     50.0      5     2.0    7.0
last store    20     30       35      4.0      0     NaN    NaN

#### We change the row index to be the data in the pants column

In [61]:
store_items = store_items.set_index('pants')
store_items

hats  watches  glasses  shoes  shirts  suits
pants                                              
30       20       35      NaN      8    15.0   45.0
5        15       10     50.0      5     2.0    7.0
30       20       35      4.0      0     NaN    NaN

In [63]:
items2 = [{'bikes': 20, 'pants': 30, 'watches': 35, 'shirts': 15, 'shoes':8, 'suits':45},
          {'watches': 10, 'glasses': 50, 'bikes': 15, 'pants':5, 'shirts': 2, 'shoes':5, 'suits':7},
          {'bikes': 20, 'pants': 30, 'watches': 35, 'glasses': 4, 'shoes':10}]

In [64]:
store_items = pd.DataFrame(items2, index=['store 1', 'store 2', 'store 3'])
store_items

bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      NaN
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     NaN     10    NaN      4.0

In [66]:
# We count the number of NaN values in store_items
x =  store_items.isnull().sum().sum()
x

3

In [67]:
store_items.fillna(0)

bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      0.0
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     0.0     10    0.0      4.0

In [68]:
store_items.fillna(method='backfill', axis=1)

bikes  pants  watches  shirts  shoes  suits  glasses
store 1   20.0   30.0     35.0    15.0    8.0   45.0      NaN
store 2   15.0    5.0     10.0     2.0    5.0    7.0     50.0
store 3   20.0   30.0     35.0    10.0   10.0    4.0      4.0

In [69]:
store_items.fillna(0)

bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      0.0
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     0.0     10    0.0      4.0

In [70]:
store_items.fillna(method='backfill', axis=0)

bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0     50.0
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     NaN     10    NaN      4.0

In [72]:
store_items.fillna(0)

bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      0.0
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     0.0     10    0.0      4.0

In [73]:
store_items.interpolate(method='linear', axis=1)

bikes  pants  watches  shirts  shoes  suits  glasses
store 1   20.0   30.0     35.0    15.0    8.0   45.0     45.0
store 2   15.0    5.0     10.0     2.0    5.0    7.0     50.0
store 3   20.0   30.0     35.0    22.5   10.0    7.0      4.0

In [74]:
store_items.interpolate(method='linear', axis=0)

bikes  pants  watches  shirts  shoes  suits  glasses
store 1     20     30       35    15.0      8   45.0      NaN
store 2     15      5       10     2.0      5    7.0     50.0
store 3     20     30       35     2.0     10    7.0      4.0

### Task

<b> Since we will be working with ratings, we will set the precision of our dataframes to one decimal place.
pd.set_option('precision', 1)

Create a Pandas DataFrame that contains the ratings some users have given to a series of books. The ratings given are in the range from 1 to 5, with 5 being the best score. The names of the books, the authors, and the ratings of each user
are given below:

    
books = pd.Series(data = ['Great Expectations', 'Of Mice and Men', 'Romeo and Juliet', 'The Time Machine', 'Alice in Wonderland' ])
authors = pd.Series(data = ['Charles Dickens', 'John Steinbeck', 'William Shakespeare', ' H. G. Wells', 'Lewis Carroll' ])

user_1 = pd.Series(data = [3.2, np.nan ,2.5])
user_2 = pd.Series(data = [5., 1.3, 4.0, 3.8])
user_3 = pd.Series(data = [2.0, 2.3, np.nan, 4])
user_4 = pd.Series(data = [4, 3.5, 4, 5, 4.2]) </b>

In [75]:
import numpy as np
import pandas as pd

In [76]:
books = pd.Series(data=['Great Expectations', 'Of Mice and Men', 'Romeo and Juliet', 'The Time Machine', 'Alice in Wonderland'])
authors = pd.Series(data=['Charles Dickens', 'John Steinback', 'William Shakespeare', 'H.G Wells', 'Lewis Carroll'])

In [77]:
user_1 = pd.Series(data=[3.2, np.nan, 2.5])
user_2 = pd.Series(data=[5.1, 1.3, 4.0, 3.8])
user_3 = pd.Series(data=[2.0, 2.3, np.nan, 4])
user_4 = pd.Series(data=[4, 3.5, 4, 5, 4.2])

<b>Users that have np.nan values means that the user has not yet rated that book. Use the data above to create a Pandas DataFrame that has the following column labels: 'Author', 'Book Title', 'User 1', 'User 2', 'User 3', 'User 4'. Let Pandas automatically assign numerical row indices to the DataFrame. Create a dictionary with the data given above<br>
dat = 
<br>Use the dictionary to create a Pandas DataFrame<br>
book_ratings = </b>

In [92]:
data = {'Book Title':books, 'Author':authors, 
       'User 1':user_1, 'User 2':user_2, 'User 3':user_3,
       'User 4':user_4}

In [93]:
book_ratings = pd.DataFrame(data)
book_ratings

Book Title               Author  User 1  User 2  User 3  User 4
0   Great Expectations      Charles Dickens     3.2     5.1     2.0     4.0
1      Of Mice and Men       John Steinback     NaN     1.3     2.3     3.5
2     Romeo and Juliet  William Shakespeare     2.5     4.0     NaN     4.0
3     The Time Machine            H.G Wells     NaN     3.8     4.0     5.0
4  Alice in Wonderland        Lewis Carroll     NaN     NaN     NaN     4.2

In [94]:
# filling NaN values with 0
book_ratings.fillna(0)#, inplace=True)

Book Title               Author  User 1  User 2  User 3  User 4
0   Great Expectations      Charles Dickens     3.2     5.1     2.0     4.0
1      Of Mice and Men       John Steinback     0.0     1.3     2.3     3.5
2     Romeo and Juliet  William Shakespeare     2.5     4.0     0.0     4.0
3     The Time Machine            H.G Wells     0.0     3.8     4.0     5.0
4  Alice in Wonderland        Lewis Carroll     0.0     0.0     0.0     4.2

In [95]:
book_ratings

Book Title               Author  User 1  User 2  User 3  User 4
0   Great Expectations      Charles Dickens     3.2     5.1     2.0     4.0
1      Of Mice and Men       John Steinback     NaN     1.3     2.3     3.5
2     Romeo and Juliet  William Shakespeare     2.5     4.0     NaN     4.0
3     The Time Machine            H.G Wells     NaN     3.8     4.0     5.0
4  Alice in Wonderland        Lewis Carroll     NaN     NaN     NaN     4.2

In [96]:
book_ratings.fillna(method='backfill')
book_ratings

Book Title               Author  User 1  User 2  User 3  User 4
0   Great Expectations      Charles Dickens     3.2     5.1     2.0     4.0
1      Of Mice and Men       John Steinback     NaN     1.3     2.3     3.5
2     Romeo and Juliet  William Shakespeare     2.5     4.0     NaN     4.0
3     The Time Machine            H.G Wells     NaN     3.8     4.0     5.0
4  Alice in Wonderland        Lewis Carroll     NaN     NaN     NaN     4.2

In [98]:
# filling NaN with mean values
book_ratings.fillna(book_ratings.mean(), inplace=True)
book_ratings

Book Title               Author  User 1  User 2    User 3  User 4
0   Great Expectations      Charles Dickens    3.20    5.10  2.000000     4.0
1      Of Mice and Men       John Steinback    2.85    1.30  2.300000     3.5
2     Romeo and Juliet  William Shakespeare    2.50    4.00  2.766667     4.0
3     The Time Machine            H.G Wells    2.85    3.80  4.000000     5.0
4  Alice in Wonderland        Lewis Carroll    2.85    3.55  2.766667     4.2

<b>From the DataFrame above you can now pick all the books that had a rating of 5.</b>

In [101]:
best_rated = book_ratings[(book_ratings == 5).any(axis=1)]['Book Title'].values
best_rated

array(['The Time Machine'], dtype=object)

## Loading Data into a pandas DataFrame

google_stock = pd.read_csv('GOOG.csv')
google_stock.head()

In [105]:
google_stock.isnull().any()

Date         False
Open         False
High         False
Low          False
Close        False
Adj Close    False
Volume       False
dtype: bool

<b>Pandas provides the .describe() method to get descriptive statistics on each column of the DataFrame. </b>

In [106]:
google_stock.describe()

Open         High          Low        Close    Adj Close  \
count  3809.000000  3809.000000  3809.000000  3809.000000  3809.000000   
mean    477.021219   481.312940   472.442959   476.979070   476.979070   
std     325.569981   328.160631   323.008258   325.744535   325.744535   
min      49.409801    50.680038    47.800831    49.818268    49.818268   
25%     235.616852   238.615616   233.484848   235.517227   235.517227   
50%     313.823700   316.558472   310.386597   313.290710   313.290710   
75%     703.619995   711.478027   695.719971   704.239990   704.239990   
max    1274.000000  1289.270020  1266.295044  1287.579956  1287.579956   

             Volume  
count  3.809000e+03  
mean   7.181291e+06  
std    8.108893e+06  
min    7.900000e+03  
25%    1.831000e+06  
50%    4.492500e+06  
75%    9.330100e+06  
max    8.254150e+07

In [107]:
google_stock.max()

Date         2019-10-04
Open               1274
High            1289.27
Low              1266.3
Close           1287.58
Adj Close       1287.58
Volume         82541500
dtype: object

In [108]:
google_stock['Close'].min()

49.818267999999996

In [109]:
google_stock.mean()

Open         4.770212e+02
High         4.813129e+02
Low          4.724430e+02
Close        4.769791e+02
Adj Close    4.769791e+02
Volume       7.181291e+06
dtype: float64

In [110]:
google_stock.corr()

Open      High       Low     Close  Adj Close    Volume
Open       1.000000  0.999901  0.999863  0.999757   0.999757 -0.552545
High       0.999901  1.000000  0.999842  0.999876   0.999876 -0.550987
Low        0.999863  0.999842  1.000000  0.999904   0.999904 -0.554739
Close      0.999757  0.999876  0.999904  1.000000   1.000000 -0.552944
Adj Close  0.999757  0.999876  0.999904  1.000000   1.000000 -0.552944
Volume    -0.552545 -0.550987 -0.554739 -0.552944  -0.552944  1.000000

In [117]:
data = pd.read_csv('fake_company.csv')
data

Year     Name Department  Age  Salary\t
0  1990    Alice         HR   25     50000
1  1990      Bob         RD   30     48000
2  1990  Charlie      Admin   45     55000
3  1991    Alice         HR   26     52000
4  1991      Bob         RD   31     50000
5  1991  Charlie      Admin   46     60000
6  1992    Alice         HR   27     60000
7  1992      Bob         RD   32     52000
8  1992  Charlie      Admin   47     62000

In [113]:
data.groupby(['Year'])['Salary\t'].sum()

Year
1990    153000
1991    162000
1992    174000
Name: Salary\t, dtype: int64

In [115]:
data.groupby(['Year'])['Salary\t'].mean()

Year
1990    51000
1991    54000
1992    58000
Name: Salary\t, dtype: int64

In [116]:
data.groupby(['Name'])['Salary\t'].sum()

Name
Alice      162000
Bob        150000
Charlie    177000
Name: Salary\t, dtype: int64

In [119]:
data.groupby(['Year', 'Department'])['Salary\t'].sum()

Year  Department
1990  Admin         55000
      HR            50000
      RD            48000
1991  Admin         60000
      HR            52000
      RD            50000
1992  Admin         62000
      HR            60000
      RD            52000
Name: Salary\t, dtype: int64